version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3001:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
